### ISSUE TITLE
Height range of color scale

### ISSUE THREAD

**Issue by sotaro915** [ToruNiina/afmize#2]
Hello!
It would be grateful if a height range of color scale for AFM images can be specified explicitly.
This leads to easily making and comparing pseudo AFM videos. 
Additionally, it would be helpful if information on the height range used is available.

Best regards,
Sotaro

**Comment by ToruNiina** [comment]
Hi,

Thank you for the suggestion!

> It would be grateful if a height range of color scale for AFM images can be specified explicitly.

True. I will implement that feature. But the thing is the way to handle values that exceed the range. In that case, I think it is good to simply raise an error to avoid confusion.

> information on the height range used.

Currently, it just uses the minimum and the maximum value in the image.
You mean, you need a color bar so that one can see the relationships between color and height? It sounds nice, but currently I don't have any plan to support such a stuff.
Since there are a number of plotting libraries, e.g. `matplotlib`,  you can read the output from this tool and plot it in any way you want. This tool is for generating AFM image like data from a molecular model, but not a plotting library. The reason why it writes image files is to take a glance. To plot images in a nicer way, I think it is good to use a tool for plotting.

**Comment by sotaro915** [comment]
Hi,

Thank you for your prompt reply and update!

> But the thing is the way to handle values that exceed the range. In that case, I think it is good to simply raise an error to avoid confusion.

I think it is better to return not error but warning. When exceeding the range, how about if the color corresponding to max/min  values of the range are used?

> You mean, you need a color bar so that one can see the relationships between color and height? It sounds nice, but currently I don't have any plan to support such a stuff.

OK. I'll follow your suggestion.
