### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by FidanSumbul** [ToruNiina/afmize#8]
I am using a MAC OSX computer and I have installed the CMake and git but in principle Xcode should have the C++14 compiler. However, when run git submodule update —init command, I am receiving the following error message. 

fatal: not a git repository (or any of the parent directories): .git

I dont know what is the reason. 
IS there a specific directory that I should go?

Thank you for your reply.

Best regards,

**Comment by ToruNiina** [comment]
It seems that you downloaded the release zip or tar file that is generated by GitHub automatically. GitHub does not include any git-related files in the compressed release file, thus git can not find the submodule information. It is confusing, so I will add the explanation to README later and try to include submodule-related files in release tarball.

Could you download the repository via `git clone https://github.com/ToruNiina/afmize.git`, instead of zip/tar file? It should work, I think.

I hope it resolves your problem.

**Comment by ToruNiina** [comment]
I updated the README. Closing.
